//<script>
(function ($) {
	var labels = <?php echo json_encode(array(
			'button'  => ossn_print('sreda:giphy:button'),
			'title'   => ossn_print('sreda:giphy:title'),
			'find'    => ossn_print('sreda:giphy:find'),
			'search'  => ossn_print('sreda:giphy:search'),
			'remove'  => ossn_print('sreda:giphy:remove'),
			'loading' => ossn_print('sreda:giphy:loading'),
			'error'   => ossn_print('sreda:giphy:load:error'),
			'empty'   => ossn_print('sreda:giphy:no:results'),
			'close'   => ossn_print('sreda:giphy:close'),
			'preview' => ossn_print('sreda:giphy:preview'),
			'powered' => ossn_print('sreda:giphy:powered'),
			'linkButton' => ossn_print('sreda:link:button'),
			'linkTitle' => ossn_print('sreda:link:title'),
			'linkInput' => ossn_print('sreda:link:input'),
			'linkPreview' => ossn_print('sreda:link:preview'),
			'linkLoading' => ossn_print('sreda:link:loading'),
			'linkError' => ossn_print('sreda:link:error'),
			'linkRemove' => ossn_print('sreda:link:remove'),
			'linkReplace' => ossn_print('sreda:link:replace'),
			'linkNoTitle' => ossn_print('sreda:link:no:title'),
	), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP); ?>;
	var searchDelay = false;

	function normalizeGiphyImageUrl(url) {
		return String(url || '').trim().replace(/^http:\/\//i, 'https://').split(/[?#]/)[0];
	}

	function isValidGiphyImage(id, url) {
		url = normalizeGiphyImageUrl(url);
		var match = url.match(/^https:\/\/media[0-9]+\.giphy\.com\/media\/([^\/?#\s]{1,128})(?:\/[^?#\s]+)+$/i);
		return /^[^\/?#\s]{1,128}$/.test(id || '')
			&& !!match
			&& String(id).toLowerCase() === match[1].toLowerCase();
	}

	function getGiphyResult(image) {
		var url = normalizeGiphyImageUrl(image && image.thumb);
		var match = url.match(/^https:\/\/media[0-9]+\.giphy\.com\/media\/([^\/?#\s]{1,128})(?:\/[^?#\s]+)+$/i);
		if (!match) {
			return false;
		}
		var id = String(image && image.id || '').trim();
		/* The URL is generated by OssnGiphy. Use its path id if an OSSN/Giphy
		 * version serializes the separate id field differently. */
		if (!isValidGiphyImage(id, url) || id.toLowerCase() !== match[1].toLowerCase()) {
			id = match[1];
		}
		return {id: id, url: url};
	}

	function isSuccessfulGiphyResponse(data) {
		return !!(data && (data.success === true || data.success === 1
			|| data.success === '1' || data.success === 'true'));
	}

	function getComposer(element) {
		return $(element).closest('.ossn-wall-container-data');
	}

	function isValidLinkPreviewUrl(url) {
		url = String(url || '').trim();
		if (!/^https?:\/\/[^\s]+$/i.test(url)) {
			return false;
		}
		var link = document.createElement('a');
		link.href = url;
		return /^https?:$/i.test(link.protocol) && !!link.hostname;
	}

	function closeLinkPanel($panel) {
		$panel.removeClass('is-open').attr('hidden', 'hidden');
	}

	function closeAllLinkPanels(except) {
		$('.sreda-link-preview-panel.is-open').each(function () {
			if (!except || this !== except[0]) {
				closeLinkPanel($(this));
			}
		});
	}

	function setLinkStatus($panel, text, isError) {
		var $status = $panel.find('.sreda-link-preview-status');
		$status.text(text || '').toggle(!!text).toggleClass('is-error', !!isError);
		if (text) {
			$status.removeAttr('hidden');
		} else {
			$status.attr('hidden', 'hidden');
		}
	}

	function createLinkPreviewPanel($composer) {
		var $panel = $composer.children('.sreda-link-preview-panel');
		if ($panel.length) {
			return $panel;
		}

		$panel = $('<div>', {
			'class': 'sreda-link-preview-panel',
			'role': 'dialog',
			'aria-label': labels.linkTitle,
		});
		$panel.attr('hidden', 'hidden');

		var $header = $('<div>', {'class': 'sreda-link-preview-header'});
		$header.append($('<strong>').text(labels.linkTitle));
		$header.append($('<button>', {
			type: 'button',
			'class': 'sreda-link-preview-close',
			'aria-label': labels.close,
		}).text('×'));

		var $row = $('<div>', {'class': 'sreda-link-preview-row'});
		$row.append($('<input>', {
			type: 'url',
			'class': 'sreda-link-preview-input',
			'placeholder': labels.linkInput,
		}));
		$row.find('input').attr({autocomplete: 'off', inputmode: 'url'});
		$row.append($('<button>', {
			type: 'button',
			'class': 'sreda-link-preview-submit',
		}).text(labels.linkPreview));

		$panel.append($header);
		$panel.append($row);
		$panel.append($('<div>', {
			'class': 'sreda-link-preview-status',
			hidden: true,
		}));
		$panel.append($('<div>', {
			'class': 'sreda-link-preview-selection',
			hidden: true,
		}));

		var $controls = $composer.children('.controls').first();
		if ($controls.length) {
			$panel.insertAfter($controls);
		} else {
			$composer.append($panel);
		}
		return $panel;
	}

	function clearLinkPreview($composer, clearInput) {
		var $panel = $composer.children('.sreda-link-preview-panel');
		var delay = $panel.data('sreda-link-preview-delay');
		if (delay) {
			clearTimeout(delay);
		}
		$panel.removeData('sreda-link-preview-delay');
		var xhr = $panel.data('sreda-link-preview-xhr');
		if (xhr && xhr.readyState !== 4) {
			xhr.abort();
		}
		$panel.removeData('sreda-link-preview-xhr');
		$composer.find('input[name^="sreda_link_preview_"]').remove();
		$panel.find('.sreda-link-preview-selection').empty().attr('hidden', 'hidden');
		setLinkStatus($panel, '', false);
		if (clearInput) {
			$panel.find('.sreda-link-preview-input').val('');
		}
	}

	function setLinkPreview($composer, data) {
		var url = String(data && data.url || '').trim();
		if (!data || !data.success || !isValidLinkPreviewUrl(url)) {
			return false;
		}
		clearLinkPreview($composer, false);
		ensureHiddenField($composer, 'sreda_link_preview_url', url);
		ensureHiddenField($composer, 'sreda_link_preview_title', String(data.title || labels.linkNoTitle));
		ensureHiddenField($composer, 'sreda_link_preview_description', String(data.description || ''));
		ensureHiddenField($composer, 'sreda_link_preview_site_name', String(data.site_name || data.domain || ''));
		ensureHiddenField($composer, 'sreda_link_preview_image', String(data.image || ''));
		ensureHiddenField($composer, 'sreda_link_preview_favicon', String(data.favicon || ''));

		var $selection = $composer.children('.sreda-link-preview-panel').find('.sreda-link-preview-selection');
		$selection.empty();
		if (data.image) {
			$selection.append($('<img>', {
				'class': 'sreda-link-preview-selection-image',
				'alt': '',
				'loading': 'lazy',
			}).attr('src', String(data.image)));
		}
		var $content = $('<div>', {'class': 'sreda-link-preview-selection-content'});
		$content.append($('<strong>', {'class': 'sreda-link-preview-selection-title'}).text(String(data.title || labels.linkNoTitle)));
		if (data.description) {
			$content.append($('<span>', {'class': 'sreda-link-preview-selection-description'}).text(String(data.description)));
		}
		$content.append($('<span>', {'class': 'sreda-link-preview-selection-domain'}).text(String(data.domain || data.site_name || '')));
		$content.append($('<button>', {
			type: 'button',
			'class': 'sreda-link-preview-selection-remove',
		}).text(labels.linkRemove));
		$selection.append($content).removeAttr('hidden');
		$composer.children('.sreda-link-preview-panel').find('.sreda-link-preview-input').val(url);
		return true;
	}

	function loadLinkPreview($panel) {
		var $composer = getComposer($panel);
		var url = String($panel.find('.sreda-link-preview-input').val() || '').trim();
		if (!isValidLinkPreviewUrl(url)) {
			clearLinkPreview($composer, false);
			setLinkStatus($panel, labels.linkError, true);
			return;
		}
		var current = $panel.data('sreda-link-preview-xhr');
		if (current && current.readyState !== 4) {
			current.abort();
		}
		clearLinkPreview($composer, false);
		setLinkStatus($panel, labels.linkLoading, false);
		if (!window.Ossn || typeof Ossn.PostRequest !== 'function') {
			setLinkStatus($panel, labels.linkError, true);
			return;
		}
		var request = Ossn.PostRequest({
			url: Ossn.site_url + 'action/sreda/link/preview',
			params: 'url=' + encodeURIComponent(url),
			callback: function (data) {
				if (String($panel.find('.sreda-link-preview-input').val() || '').trim() !== url) {
					return;
				}
				if (typeof data === 'string') {
					try {
						data = JSON.parse(data);
					} catch (error) {
						data = null;
					}
				}
				if (setLinkPreview($composer, data)) {
					setLinkStatus($panel, '', false);
				} else {
					setLinkStatus($panel, labels.linkError, true);
				}
			},
			error: function () {
				if (String($panel.find('.sreda-link-preview-input').val() || '').trim() !== url) {
					return;
				}
				setLinkStatus($panel, labels.linkError, true);
			},
		});
		$panel.data('sreda-link-preview-xhr', request);
	}

	function closePicker($picker) {
		$picker.removeClass('is-open').attr('hidden', 'hidden').css({
			left: '',
			top: '',
			width: '',
		});
	}

	function closeAllPickers(except) {
		$('.sreda-giphy-wall-picker.is-open').each(function () {
			if (!except || this !== except[0]) {
				closePicker($(this));
			}
		});
	}

	function positionPicker($composer, $picker) {
		var control = $composer.find('.sreda-giphy-wall-control')[0];
		if (!control) {
			return;
		}
		var rect = control.getBoundingClientRect();
		var viewport = window.visualViewport || null;
		var viewportWidth = viewport ? viewport.width : window.innerWidth;
		var viewportHeight = viewport ? viewport.height : window.innerHeight;
		var padding = 8;
		var width = Math.min(360, Math.max(0, viewportWidth - padding * 2));
		$picker.css({
			position: 'fixed',
			width: width + 'px',
			left: '0px',
			top: '0px',
		});

		var height = $picker.outerHeight();
		var top = rect.bottom + 6;
		if (top + height > viewportHeight - padding) {
			top = rect.top - height - 6;
		}
		top = Math.max(padding, Math.min(top, viewportHeight - height - padding));

		var left = rect.left + (rect.width / 2) - (width / 2);
		left = Math.max(padding, Math.min(left, viewportWidth - width - padding));
		$picker.css({left: left + 'px', top: top + 'px'});
	}

	function createPicker($composer) {
		var $picker = $composer.children('.sreda-giphy-wall-picker');
		if ($picker.length) {
			return $picker;
		}

		$picker = $('<div>', {
			'class': 'sreda-giphy-wall-picker',
			'role': 'dialog',
			'aria-label': labels.title,
			hidden: true,
		});
		var $header = $('<div>', {'class': 'sreda-giphy-wall-picker-header'});
		$header.append($('<strong>').text(labels.title));
		$header.append($('<button>', {
			type: 'button',
			'class': 'sreda-giphy-wall-picker-close',
			'aria-label': labels.close,
		}).text('×'));

		var $searchRow = $('<div>', {'class': 'sreda-giphy-wall-search-row'});
		var $searchInput = $('<input>', {
			type: 'search',
			'class': 'sreda-giphy-wall-search',
			'placeholder': labels.search,
		});
		/* jQuery UI treats "autocomplete" in the element-properties object
		 * as a plugin method call. Set it as a real HTML attribute instead. */
		$searchInput.attr('autocomplete', 'off');
		$searchRow.append($searchInput);
		$searchRow.append($('<button>', {
			type: 'button',
			'class': 'sreda-giphy-wall-search-submit',
		}).text(labels.find));

		$picker.append($header);
		$picker.append($searchRow);
		$picker.append($('<div>', {'class': 'sreda-giphy-wall-powered'}).text(labels.powered));
		var $results = $('<div>', {'class': 'sreda-giphy-wall-results', 'role': 'list'});
		$results.on('scroll.sredaGiphyWall', function () {
			if (this.scrollTop + this.clientHeight >= this.scrollHeight - 96) {
				loadNextGiphyPage($picker);
			}
		});
		$picker.append($results);
		$picker.append($('<div>', {
			'class': 'sreda-giphy-wall-status',
			hidden: true,
		}));
		$composer.append($picker);
		$picker.data({
			'sreda-giphy-page': 0,
			'sreda-giphy-keyword': '',
			'sreda-giphy-has-more': true,
			'sreda-giphy-loading': false,
			'sreda-giphy-seen': {},
		});
		return $picker;
	}

	function setStatus($picker, text, isError) {
		var $status = $picker.find('.sreda-giphy-wall-status');
		var visible = !!text;
		$status.text(text || '').toggle(visible).toggleClass('is-error', !!isError);
		if (visible) {
			$status.removeAttr('hidden');
		} else {
			$status.attr('hidden', 'hidden');
		}
	}

	function renderResults($picker, images, append) {
		var $results = $picker.find('.sreda-giphy-wall-results');
		if (!append) {
			$results.empty();
		}
		$results.removeClass('is-loading');
		setStatus($picker, '', false);
		if (!images || !images.length) {
			if (!append || !$results.children().length) {
				setStatus($picker, labels.empty, false);
			}
			return;
		}
		var seen = $picker.data('sreda-giphy-seen') || {};
		var added = 0;
		$.each(images, function () {
			var result = getGiphyResult(this);
			if (!result) {
				return;
			}
			var id = result.id;
			var url = result.url;
			if (seen[id]) {
				return;
			}
			seen[id] = true;
			added++;
			var $result = $('<button>', {
				type: 'button',
				'class': 'sreda-giphy-wall-result',
				'role': 'listitem',
				'aria-label': labels.preview,
			}).attr({
				'data-giphy-id': id,
				'data-giphy-url': url,
			});
			$result.append($('<img>', {
				src: url,
				alt: labels.preview,
				loading: 'lazy',
			}));
			$results.append($result);
		});
		$picker.data('sreda-giphy-seen', seen);
		if (!$results.children().length) {
			setStatus($picker, labels.error, true);
		}
		return added;
	}

	function updateGiphyPagination($picker, data, page, added) {
		var pagination = data && data.pagination ? data.pagination : {};
		var total = parseInt(pagination.total_count, 10);
		var offset = parseInt(pagination.offset, 10);
		var count = parseInt(pagination.count, 10);
		var hasMore = added > 0;
		if (!isNaN(total) && !isNaN(offset)) {
			if (isNaN(count) || count < 1) {
				count = added;
			}
			hasMore = total > (offset + count);
		} else if (data && data.pagination_code) {
			hasMore = true;
		}
		if (!added) {
			hasMore = false;
		}
		$picker.data({
			'sreda-giphy-page': page,
			'sreda-giphy-has-more': hasMore,
		});
	}

	function maybeLoadNextGiphyPage($picker) {
		var results = $picker.find('.sreda-giphy-wall-results')[0];
		if (!results || !$picker.data('sreda-giphy-has-more')) {
			return;
		}
		if (results.scrollHeight <= results.clientHeight + 8) {
			setTimeout(function () {
				loadNextGiphyPage($picker);
			}, 0);
		}
	}

	function loadNextGiphyPage($picker) {
		if (!$picker.hasClass('is-open')
			|| $picker.data('sreda-giphy-loading')
			|| !$picker.data('sreda-giphy-has-more')) {
			return;
		}
		var keyword = String($picker.data('sreda-giphy-keyword') || '');
		var currentPage = parseInt($picker.data('sreda-giphy-page'), 10) || 1;
		searchGiphy($picker, keyword, currentPage + 1, true);
	}

	function startGiphySearch($picker, keyword) {
		var query = String(keyword || '').trim();
		$picker.data({
			'sreda-giphy-page': 0,
			'sreda-giphy-keyword': query,
			'sreda-giphy-has-more': true,
			'sreda-giphy-seen': {},
		});
		searchGiphy($picker, query, 1, false);
	}

	function searchGiphy($picker, keyword, page, append) {
		var current = $picker.data('sreda-giphy-xhr');
		if (current && current.readyState !== 4) {
			current.abort();
		}
		var $results = $picker.find('.sreda-giphy-wall-results');
		$results.addClass('is-loading');
		if (!append) {
			$results.empty();
		}
		setStatus($picker, labels.loading, false);
		var query = String(keyword || '').trim();
		var requestPage = parseInt(page, 10) || 1;
		var requestToken = (parseInt($picker.data('sreda-giphy-request-token'), 10) || 0) + 1;
		$picker.data({
			'sreda-giphy-loading': true,
			'sreda-giphy-request-token': requestToken,
			'sreda-giphy-keyword': query,
		});
		if (!window.Ossn || typeof Ossn.PostRequest !== 'function') {
			$results.removeClass('is-loading');
			$picker.data('sreda-giphy-loading', false);
			setStatus($picker, labels.error, true);
			return;
		}
		var request = Ossn.PostRequest({
			/* Use the exact action consumed by the working comment picker. */
			url: Ossn.site_url + 'action/giphy/search?keyword=' + encodeURIComponent(query) + '&offset_giphy=' + requestPage,
			callback: function (data) {
				if (requestToken !== $picker.data('sreda-giphy-request-token')) {
					return;
				}
				$results.removeClass('is-loading');
				$picker.data('sreda-giphy-loading', false);
				if (typeof data === 'string') {
					try {
						data = JSON.parse(data);
					} catch (error) {
						data = null;
					}
				}
				/* Match the response check used by the working OssnGiphy
				 * comment picker; OSSN versions may serialize this as 1/true. */
				/* Some OSSN builds append a second JSON envelope to an action
				 * response. The image list is the authoritative success signal. */
				if (data && data.images && typeof data.images.length !== 'undefined') {
					var added = renderResults($picker, data.images || [], !!append);
					updateGiphyPagination($picker, data, requestPage, added);
					if (added || $results.children().length) {
						setStatus($picker, '', false);
					}
					maybeLoadNextGiphyPage($picker);
				} else if (isSuccessfulGiphyResponse(data)) {
					var fallbackAdded = renderResults($picker, data.images || [], !!append);
					updateGiphyPagination($picker, data, requestPage, fallbackAdded);
					if (fallbackAdded || $results.children().length) {
						setStatus($picker, '', false);
					}
					maybeLoadNextGiphyPage($picker);
				} else {
					$picker.data('sreda-giphy-has-more', false);
					setStatus($picker, labels.error, true);
				}
			},
			error: function () {
				if (requestToken !== $picker.data('sreda-giphy-request-token')) {
					return;
				}
				$results.removeClass('is-loading');
				$picker.data({
					'sreda-giphy-loading': false,
					'sreda-giphy-has-more': false,
				});
				setStatus($picker, labels.error, true);
			},
		});
		$picker.data('sreda-giphy-xhr', request);
	}

	function ensureHiddenField($composer, name, value) {
		var $field = $composer.find('input[name="' + name + '"]');
		if (!$field.length) {
			$field = $('<input>', {type: 'hidden', name: name});
			$composer.append($field);
		}
		$field.val(value);
	}

	function clearAttachment($composer) {
		$composer.find('input[name="sreda_giphy_id"], input[name="sreda_giphy_url"]').remove();
		var $preview = $composer.find('.sreda-giphy-wall-preview');
		$preview.attr('hidden', 'hidden').find('img').attr('src', '');
	}

	function setAttachment($composer, id, url) {
		url = normalizeGiphyImageUrl(url);
		if (!isValidGiphyImage(id, url)) {
			return;
		}
		ensureHiddenField($composer, 'sreda_giphy_id', id);
		ensureHiddenField($composer, 'sreda_giphy_url', url);

		/* Keep the first version to one visual attachment per post. */
		$composer.find('#ossn-wall-photo input[type="file"]').val('');
		$composer.find('#ossn-wall-photo').hide();

		var $preview = $composer.find('.sreda-giphy-wall-preview');
		if (!$preview.length) {
			$preview = $('<div>', {
				'class': 'sreda-giphy-wall-preview',
				'role': 'status',
			});
			$preview.append($('<img>', {alt: labels.preview}));
			$preview.append($('<button>', {
				type: 'button',
				'class': 'sreda-giphy-wall-preview-remove',
			}).text(labels.remove));
			$preview.insertAfter($composer.find('.controls'));
		}
		$preview.removeAttr('hidden').find('img').attr('src', url);
	}

	$(document).on('click', '.sreda-link-preview-control', function (event) {
		event.preventDefault();
		event.stopPropagation();
		var $composer = getComposer(this);
		var $panel = createLinkPreviewPanel($composer);
		var open = !$panel.hasClass('is-open');
		closeAllLinkPanels($panel);
		closeAllPickers();
		if (open) {
			$panel.addClass('is-open').removeAttr('hidden');
			setTimeout(function () {
				$panel.find('.sreda-link-preview-input').trigger('focus');
			}, 0);
		}
	});

	$(document).on('click', '.sreda-link-preview-panel', function (event) {
		event.stopPropagation();
	});

	$(document).on('click', '.sreda-link-preview-close', function () {
		closeLinkPanel($(this).closest('.sreda-link-preview-panel'));
	});

	$(document).on('click', '.sreda-link-preview-submit', function () {
		loadLinkPreview($(this).closest('.sreda-link-preview-panel'));
	});

	$(document).on('keydown', '.sreda-link-preview-input', function (event) {
		if (event.key === 'Enter') {
			event.preventDefault();
			loadLinkPreview($(this).closest('.sreda-link-preview-panel'));
		}
	});

	$(document).on('input paste', '.sreda-link-preview-input', function () {
		var $input = $(this);
		var $panel = $input.closest('.sreda-link-preview-panel');
		var $composer = getComposer(this);
		var value = String($input.val() || '').trim();
		var selectedUrl = String($composer.find('input[name="sreda_link_preview_url"]').val() || '').trim();
		if (selectedUrl && selectedUrl !== value) {
			clearLinkPreview($composer, false);
		}
		clearTimeout($panel.data('sreda-link-preview-delay'));
		if (!value || !isValidLinkPreviewUrl(value)) {
			if (!value) {
				clearLinkPreview($composer, false);
			}
			return;
		}
		var delay = setTimeout(function () {
			loadLinkPreview($panel);
		}, 450);
		$panel.data('sreda-link-preview-delay', delay);
	});

	$(document).on('click', '.sreda-link-preview-selection-remove', function () {
		clearLinkPreview(getComposer(this), true);
	});

	$(document).on('click', '.sreda-giphy-wall-control', function (event) {
		event.preventDefault();
		event.stopPropagation();
		var $composer = getComposer(this);
		var $picker = createPicker($composer);
		var open = !$picker.hasClass('is-open');
		closeAllPickers($picker);
		if (open) {
			$picker.addClass('is-open').removeAttr('hidden');
			positionPicker($composer, $picker);
			if (!$picker.data('sreda-giphy-loaded')) {
				$picker.data('sreda-giphy-loaded', true);
				startGiphySearch($picker, '');
			}
		}
	});

	$(document).on('click', '.sreda-giphy-wall-picker', function (event) {
		event.stopPropagation();
	});

	$(document).on('click', '.sreda-giphy-wall-picker-close', function () {
		closePicker($(this).closest('.sreda-giphy-wall-picker'));
	});

	$(document).on('click', '.sreda-giphy-wall-search-submit', function () {
		var $picker = $(this).closest('.sreda-giphy-wall-picker');
		startGiphySearch($picker, $picker.find('.sreda-giphy-wall-search').val());
	});

	$(document).on('keydown', '.sreda-giphy-wall-search', function (event) {
		if (event.key === 'Enter') {
			event.preventDefault();
			startGiphySearch($(this).closest('.sreda-giphy-wall-picker'), $(this).val());
		}
	});

	$(document).on('input', '.sreda-giphy-wall-search', function () {
		var $input = $(this);
		clearTimeout(searchDelay);
		searchDelay = setTimeout(function () {
			startGiphySearch($input.closest('.sreda-giphy-wall-picker'), $input.val());
		}, 350);
	});

	$(document).on('click', '.sreda-giphy-wall-result', function () {
		var $result = $(this);
		var $composer = getComposer(this);
		setAttachment($composer, $result.attr('data-giphy-id'), $result.attr('data-giphy-url'));
		closePicker($result.closest('.sreda-giphy-wall-picker'));
	});

	$(document).on('click', '.sreda-giphy-wall-preview-remove', function () {
		clearAttachment(getComposer(this));
	});

	/* Selecting a local photo replaces a previously selected GIF. */
	$(document).on('click', '.ossn-wall-photo', function () {
		clearAttachment(getComposer(this));
	});

	/* OSSN rejects an empty wall post. A GIF-only post is still a valid post,
	 * so provide an invisible marker before OssnWall extracts the editor text.
	 * The core wall handler runs from <body>; a direct button handler runs first. */
	$(function () {
		var $wallForm = $('#ossn-wall-form');
		if (!$wallForm.length) {
			return;
		}
		var ensureAttachmentPostText = function () {
			var $form = $(this).closest('form');
			var $attachment = $form.find('input[name="sreda_giphy_url"], input[name="sreda_link_preview_url"]').filter(function () {
				return String($(this).val() || '').trim() !== '';
			}).first();
			if (!$attachment.length) {
				return;
			}
			var $editor = $form.find('.ossn-wall-textarea').first();
			if ($editor.length && $editor.text().trim() === '' && !$editor.find('img').length) {
				/* U+200B survives JavaScript/PHP trim but has no visual output. */
				$editor.text('\u200B');
			}
		};
		$wallForm.find('.ossn-wall-post').on('click.sredaGiphyWall', ensureAttachmentPostText);
		$wallForm.on('submit.sredaGiphyWall', function () {
			var $form = $(this);
			var $attachment = $form.find('input[name="sreda_giphy_url"], input[name="sreda_link_preview_url"]').filter(function () {
				return String($(this).val() || '').trim() !== '';
			}).first();
			if (!$attachment.length) {
				return;
			}
			var $post = $form.find('textarea[name="post"]').first();
			if (!$post.length) {
				$post = $('<textarea>', {name: 'post', style: 'display:none;'}).appendTo($form);
			}
			if (String($post.val() || '').trim() === '') {
				$post.val(' ');
			}
		});
	});

	$(document).on('click', function (event) {
		/* The picker button and the picker itself must not be closed by this
		 * document-level outside-click handler in the same event cycle. */
		if ($(event.target).closest('.sreda-giphy-wall-control, .sreda-giphy-wall-picker, .sreda-link-preview-control, .sreda-link-preview-panel').length) {
			return;
		}
		closeAllPickers();
		closeAllLinkPanels();
	});

	$(window).on('resize orientationchange scroll', function () {
		$('.sreda-giphy-wall-picker.is-open').each(function () {
			positionPicker(getComposer(this), $(this));
		});
	});

	if (window.visualViewport) {
		$(window.visualViewport).on('resize scroll', function () {
			$('.sreda-giphy-wall-picker.is-open').each(function () {
				positionPicker(getComposer(this), $(this));
			});
		});
	}

	/* OssnWall clears its composer after a successful wall action. */
	$(document).ajaxSuccess(function (event, xhr, settings, data) {
		var url = settings && settings.url ? settings.url : '';
		if (url.indexOf('action/wall/post') === -1 || !data || !data.success) {
			return;
		}
		$('.ossn-wall-container-data').each(function () {
			clearAttachment($(this));
			clearLinkPreview($(this), true);
		});
	});
})(jQuery);
